version: '1'

services:
  part_5:
    build: part_5/
    restart: always
    container_name: part_5
    depends_on:
      - part_6

  part_6:
    image: nginx
    volumes:
      - ./Part 6/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    container_name: part_6
    ports:
      - 80:8080
    